### ISSUE TITLE
The latest 1.4.7 library in "Releases" section has no x86_64 support

### ISSUE THREAD

**Issue by potiuk** [glock45/iOS-Hierarchy-Viewer#25]
No x86_64 support:  the instructions to add the library manually does not work :(. So it makes it difficult for someone who does not use CocoaPods.

**Comment by glock45** [comment]
Thanks Jarek !

https://github.com/glock45/iOS-Hierarchy-Viewer/releases/tag/1.4.8

**Comment by potiuk** [comment]
Cool Thanks! In the meantime I integrated Cocoapods and Hierarchy Viewer from there, but it's useful to have it in the release as well :+1:
